// Autogenerated from Pigeon (v22.5.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

package dev.snipme.snipmeapp.bridge;

import static java.lang.annotation.ElementType.METHOD;
import static java.lang.annotation.RetentionPolicy.CLASS;

import android.util.Log;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import io.flutter.plugin.common.BasicMessageChannel;
import io.flutter.plugin.common.BinaryMessenger;
import io.flutter.plugin.common.MessageCodec;
import io.flutter.plugin.common.StandardMessageCodec;
import java.io.ByteArrayOutputStream;
import java.lang.annotation.Retention;
import java.lang.annotation.Target;
import java.nio.ByteBuffer;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collections;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;

/** Generated class from Pigeon. */
@SuppressWarnings({"unused", "unchecked", "CodeBlock2Expr", "RedundantSuppression", "serial"})
public class Bridge {

  /** Error class for passing custom error details to Flutter via a thrown PlatformException. */
  public static class FlutterError extends RuntimeException {

    /** The error code. */
    public final String code;

    /** The error details. Must be a datatype supported by the api codec. */
    public final Object details;

    public FlutterError(@NonNull String code, @Nullable String message, @Nullable Object details) 
    {
      super(message);
      this.code = code;
      this.details = details;
    }
  }

  @NonNull
  protected static ArrayList<Object> wrapError(@NonNull Throwable exception) {
    ArrayList<Object> errorList = new ArrayList<>(3);
    if (exception instanceof FlutterError) {
      FlutterError error = (FlutterError) exception;
      errorList.add(error.code);
      errorList.add(error.getMessage());
      errorList.add(error.details);
    } else {
      errorList.add(exception.toString());
      errorList.add(exception.getClass().getSimpleName());
      errorList.add(
        "Cause: " + exception.getCause() + ", Stacktrace: " + Log.getStackTraceString(exception));
    }
    return errorList;
  }

  @Target(METHOD)
  @Retention(CLASS)
  @interface CanIgnoreReturnValue {}

  public enum SnippetLanguageType {
    C(0),
    CPP(1),
    OBJECTIVE_C(2),
    C_SHARP(3),
    JAVA(4),
    BASH(5),
    PYTHON(6),
    PERL(7),
    RUBY(8),
    SWIFT(9),
    JAVASCRIPT(10),
    KOTLIN(11),
    COFFEESCRIPT(12),
    RUST(13),
    BASIC(14),
    CLOJURE(15),
    CSS(16),
    DART(17),
    ERLANG(18),
    GO(19),
    HASKELL(20),
    LISP(21),
    LLVM(22),
    LUA(23),
    MATLAB(24),
    ML(25),
    MUMPS(26),
    NEMERLE(27),
    PASCAL(28),
    R(29),
    RD(30),
    SCALA(31),
    SQL(32),
    TEX(33),
    VB(34),
    VHDL(35),
    TCL(36),
    XQUERY(37),
    YAML(38),
    MARKDOWN(39),
    JSON(40),
    XML(41),
    PROTO(42),
    REGEX(43),
    UNKNOWN(44);

    final int index;

    SnippetLanguageType(final int index) {
      this.index = index;
    }
  }

  public enum SnippetFilterType {
    ALL(0),
    MINE(1),
    SHARED(2);

    final int index;

    SnippetFilterType(final int index) {
      this.index = index;
    }
  }

  public enum UserReaction {
    NONE(0),
    LIKE(1),
    DISLIKE(2);

    final int index;

    UserReaction(final int index) {
      this.index = index;
    }
  }

  public enum ModelState {
    LOADING(0),
    LOADED(1),
    ERROR(2);

    final int index;

    ModelState(final int index) {
      this.index = index;
    }
  }

  public enum MainModelEvent {
    NONE(0),
    ALERT(1),
    LOGOUT(2);

    final int index;

    MainModelEvent(final int index) {
      this.index = index;
    }
  }

  public enum DetailModelEvent {
    NONE(0),
    SAVED(1),
    DELETED(2);

    final int index;

    DetailModelEvent(final int index) {
      this.index = index;
    }
  }

  public enum LoginModelEvent {
    NONE(0),
    LOGGED(1);

    final int index;

    LoginModelEvent(final int index) {
      this.index = index;
    }
  }

  /** Generated class from Pigeon that represents data sent in messages. */
  public static final class Snippet {
    private @Nullable String uuid;

    public @Nullable String getUuid() {
      return uuid;
    }

    public void setUuid(@Nullable String setterArg) {
      this.uuid = setterArg;
    }

    private @Nullable String title;

    public @Nullable String getTitle() {
      return title;
    }

    public void setTitle(@Nullable String setterArg) {
      this.title = setterArg;
    }

    private @Nullable SnippetCode code;

    public @Nullable SnippetCode getCode() {
      return code;
    }

    public void setCode(@Nullable SnippetCode setterArg) {
      this.code = setterArg;
    }

    private @Nullable SnippetLanguage language;

    public @Nullable SnippetLanguage getLanguage() {
      return language;
    }

    public void setLanguage(@Nullable SnippetLanguage setterArg) {
      this.language = setterArg;
    }

    private @Nullable Owner owner;

    public @Nullable Owner getOwner() {
      return owner;
    }

    public void setOwner(@Nullable Owner setterArg) {
      this.owner = setterArg;
    }

    private @Nullable Boolean isOwner;

    public @Nullable Boolean getIsOwner() {
      return isOwner;
    }

    public void setIsOwner(@Nullable Boolean setterArg) {
      this.isOwner = setterArg;
    }

    private @Nullable String timeAgo;

    public @Nullable String getTimeAgo() {
      return timeAgo;
    }

    public void setTimeAgo(@Nullable String setterArg) {
      this.timeAgo = setterArg;
    }

    private @Nullable Long voteResult;

    public @Nullable Long getVoteResult() {
      return voteResult;
    }

    public void setVoteResult(@Nullable Long setterArg) {
      this.voteResult = setterArg;
    }

    private @Nullable UserReaction userReaction;

    public @Nullable UserReaction getUserReaction() {
      return userReaction;
    }

    public void setUserReaction(@Nullable UserReaction setterArg) {
      this.userReaction = setterArg;
    }

    private @Nullable Boolean isPrivate;

    public @Nullable Boolean getIsPrivate() {
      return isPrivate;
    }

    public void setIsPrivate(@Nullable Boolean setterArg) {
      this.isPrivate = setterArg;
    }

    private @Nullable Boolean isLiked;

    public @Nullable Boolean getIsLiked() {
      return isLiked;
    }

    public void setIsLiked(@Nullable Boolean setterArg) {
      this.isLiked = setterArg;
    }

    private @Nullable Boolean isDisliked;

    public @Nullable Boolean getIsDisliked() {
      return isDisliked;
    }

    public void setIsDisliked(@Nullable Boolean setterArg) {
      this.isDisliked = setterArg;
    }

    private @Nullable Boolean isSaved;

    public @Nullable Boolean getIsSaved() {
      return isSaved;
    }

    public void setIsSaved(@Nullable Boolean setterArg) {
      this.isSaved = setterArg;
    }

    private @Nullable Boolean isToDelete;

    public @Nullable Boolean getIsToDelete() {
      return isToDelete;
    }

    public void setIsToDelete(@Nullable Boolean setterArg) {
      this.isToDelete = setterArg;
    }

    @Override
    public boolean equals(Object o) {
      if (this == o) { return true; }
      if (o == null || getClass() != o.getClass()) { return false; }
      Snippet that = (Snippet) o;
      return Objects.equals(uuid, that.uuid) && Objects.equals(title, that.title) && Objects.equals(code, that.code) && Objects.equals(language, that.language) && Objects.equals(owner, that.owner) && Objects.equals(isOwner, that.isOwner) && Objects.equals(timeAgo, that.timeAgo) && Objects.equals(voteResult, that.voteResult) && Objects.equals(userReaction, that.userReaction) && Objects.equals(isPrivate, that.isPrivate) && Objects.equals(isLiked, that.isLiked) && Objects.equals(isDisliked, that.isDisliked) && Objects.equals(isSaved, that.isSaved) && Objects.equals(isToDelete, that.isToDelete);
    }

    @Override
    public int hashCode() {
      return Objects.hash(uuid, title, code, language, owner, isOwner, timeAgo, voteResult, userReaction, isPrivate, isLiked, isDisliked, isSaved, isToDelete);
    }

    public static final class Builder {

      private @Nullable String uuid;

      @CanIgnoreReturnValue
      public @NonNull Builder setUuid(@Nullable String setterArg) {
        this.uuid = setterArg;
        return this;
      }

      private @Nullable String title;

      @CanIgnoreReturnValue
      public @NonNull Builder setTitle(@Nullable String setterArg) {
        this.title = setterArg;
        return this;
      }

      private @Nullable SnippetCode code;

      @CanIgnoreReturnValue
      public @NonNull Builder setCode(@Nullable SnippetCode setterArg) {
        this.code = setterArg;
        return this;
      }

      private @Nullable SnippetLanguage language;

      @CanIgnoreReturnValue
      public @NonNull Builder setLanguage(@Nullable SnippetLanguage setterArg) {
        this.language = setterArg;
        return this;
      }

      private @Nullable Owner owner;

      @CanIgnoreReturnValue
      public @NonNull Builder setOwner(@Nullable Owner setterArg) {
        this.owner = setterArg;
        return this;
      }

      private @Nullable Boolean isOwner;

      @CanIgnoreReturnValue
      public @NonNull Builder setIsOwner(@Nullable Boolean setterArg) {
        this.isOwner = setterArg;
        return this;
      }

      private @Nullable String timeAgo;

      @CanIgnoreReturnValue
      public @NonNull Builder setTimeAgo(@Nullable String setterArg) {
        this.timeAgo = setterArg;
        return this;
      }

      private @Nullable Long voteResult;

      @CanIgnoreReturnValue
      public @NonNull Builder setVoteResult(@Nullable Long setterArg) {
        this.voteResult = setterArg;
        return this;
      }

      private @Nullable UserReaction userReaction;

      @CanIgnoreReturnValue
      public @NonNull Builder setUserReaction(@Nullable UserReaction setterArg) {
        this.userReaction = setterArg;
        return this;
      }

      private @Nullable Boolean isPrivate;

      @CanIgnoreReturnValue
      public @NonNull Builder setIsPrivate(@Nullable Boolean setterArg) {
        this.isPrivate = setterArg;
        return this;
      }

      private @Nullable Boolean isLiked;

      @CanIgnoreReturnValue
      public @NonNull Builder setIsLiked(@Nullable Boolean setterArg) {
        this.isLiked = setterArg;
        return this;
      }

      private @Nullable Boolean isDisliked;

      @CanIgnoreReturnValue
      public @NonNull Builder setIsDisliked(@Nullable Boolean setterArg) {
        this.isDisliked = setterArg;
        return this;
      }

      private @Nullable Boolean isSaved;

      @CanIgnoreReturnValue
      public @NonNull Builder setIsSaved(@Nullable Boolean setterArg) {
        this.isSaved = setterArg;
        return this;
      }

      private @Nullable Boolean isToDelete;

      @CanIgnoreReturnValue
      public @NonNull Builder setIsToDelete(@Nullable Boolean setterArg) {
        this.isToDelete = setterArg;
        return this;
      }

      public @NonNull Snippet build() {
        Snippet pigeonReturn = new Snippet();
        pigeonReturn.setUuid(uuid);
        pigeonReturn.setTitle(title);
        pigeonReturn.setCode(code);
        pigeonReturn.setLanguage(language);
        pigeonReturn.setOwner(owner);
        pigeonReturn.setIsOwner(isOwner);
        pigeonReturn.setTimeAgo(timeAgo);
        pigeonReturn.setVoteResult(voteResult);
        pigeonReturn.setUserReaction(userReaction);
        pigeonReturn.setIsPrivate(isPrivate);
        pigeonReturn.setIsLiked(isLiked);
        pigeonReturn.setIsDisliked(isDisliked);
        pigeonReturn.setIsSaved(isSaved);
        pigeonReturn.setIsToDelete(isToDelete);
        return pigeonReturn;
      }
    }

    @NonNull
    ArrayList<Object> toList() {
      ArrayList<Object> toListResult = new ArrayList<>(14);
      toListResult.add(uuid);
      toListResult.add(title);
      toListResult.add(code);
      toListResult.add(language);
      toListResult.add(owner);
      toListResult.add(isOwner);
      toListResult.add(timeAgo);
      toListResult.add(voteResult);
      toListResult.add(userReaction);
      toListResult.add(isPrivate);
      toListResult.add(isLiked);
      toListResult.add(isDisliked);
      toListResult.add(isSaved);
      toListResult.add(isToDelete);
      return toListResult;
    }

    static @NonNull Snippet fromList(@NonNull ArrayList<Object> pigeonVar_list) {
      Snippet pigeonResult = new Snippet();
      Object uuid = pigeonVar_list.get(0);
      pigeonResult.setUuid((String) uuid);
      Object title = pigeonVar_list.get(1);
      pigeonResult.setTitle((String) title);
      Object code = pigeonVar_list.get(2);
      pigeonResult.setCode((SnippetCode) code);
      Object language = pigeonVar_list.get(3);
      pigeonResult.setLanguage((SnippetLanguage) language);
      Object owner = pigeonVar_list.get(4);
      pigeonResult.setOwner((Owner) owner);
      Object isOwner = pigeonVar_list.get(5);
      pigeonResult.setIsOwner((Boolean) isOwner);
      Object timeAgo = pigeonVar_list.get(6);
      pigeonResult.setTimeAgo((String) timeAgo);
      Object voteResult = pigeonVar_list.get(7);
      pigeonResult.setVoteResult((Long) voteResult);
      Object userReaction = pigeonVar_list.get(8);
      pigeonResult.setUserReaction((UserReaction) userReaction);
      Object isPrivate = pigeonVar_list.get(9);
      pigeonResult.setIsPrivate((Boolean) isPrivate);
      Object isLiked = pigeonVar_list.get(10);
      pigeonResult.setIsLiked((Boolean) isLiked);
      Object isDisliked = pigeonVar_list.get(11);
      pigeonResult.setIsDisliked((Boolean) isDisliked);
      Object isSaved = pigeonVar_list.get(12);
      pigeonResult.setIsSaved((Boolean) isSaved);
      Object isToDelete = pigeonVar_list.get(13);
      pigeonResult.setIsToDelete((Boolean) isToDelete);
      return pigeonResult;
    }
  }

  /** Generated class from Pigeon that represents data sent in messages. */
  public static final class SnippetCode {
    private @Nullable String raw;

    public @Nullable String getRaw() {
      return raw;
    }

    public void setRaw(@Nullable String setterArg) {
      this.raw = setterArg;
    }

    private @Nullable List<SyntaxToken> tokens;

    public @Nullable List<SyntaxToken> getTokens() {
      return tokens;
    }

    public void setTokens(@Nullable List<SyntaxToken> setterArg) {
      this.tokens = setterArg;
    }

    @Override
    public boolean equals(Object o) {
      if (this == o) { return true; }
      if (o == null || getClass() != o.getClass()) { return false; }
      SnippetCode that = (SnippetCode) o;
      return Objects.equals(raw, that.raw) && Objects.equals(tokens, that.tokens);
    }

    @Override
    public int hashCode() {
      return Objects.hash(raw, tokens);
    }

    public static final class Builder {

      private @Nullable String raw;

      @CanIgnoreReturnValue
      public @NonNull Builder setRaw(@Nullable String setterArg) {
        this.raw = setterArg;
        return this;
      }

      private @Nullable List<SyntaxToken> tokens;

      @CanIgnoreReturnValue
      public @NonNull Builder setTokens(@Nullable List<SyntaxToken> setterArg) {
        this.tokens = setterArg;
        return this;
      }

      public @NonNull SnippetCode build() {
        SnippetCode pigeonReturn = new SnippetCode();
        pigeonReturn.setRaw(raw);
        pigeonReturn.setTokens(tokens);
        return pigeonReturn;
      }
    }

    @NonNull
    ArrayList<Object> toList() {
      ArrayList<Object> toListResult = new ArrayList<>(2);
      toListResult.add(raw);
      toListResult.add(tokens);
      return toListResult;
    }

    static @NonNull SnippetCode fromList(@NonNull ArrayList<Object> pigeonVar_list) {
      SnippetCode pigeonResult = new SnippetCode();
      Object raw = pigeonVar_list.get(0);
      pigeonResult.setRaw((String) raw);
      Object tokens = pigeonVar_list.get(1);
      pigeonResult.setTokens((List<SyntaxToken>) tokens);
      return pigeonResult;
    }
  }

  /** Generated class from Pigeon that represents data sent in messages. */
  public static final class SyntaxToken {
    private @Nullable Long start;

    public @Nullable Long getStart() {
      return start;
    }

    public void setStart(@Nullable Long setterArg) {
      this.start = setterArg;
    }

    private @Nullable Long end;

    public @Nullable Long getEnd() {
      return end;
    }

    public void setEnd(@Nullable Long setterArg) {
      this.end = setterArg;
    }

    private @Nullable Long color;

    public @Nullable Long getColor() {
      return color;
    }

    public void setColor(@Nullable Long setterArg) {
      this.color = setterArg;
    }

    @Override
    public boolean equals(Object o) {
      if (this == o) { return true; }
      if (o == null || getClass() != o.getClass()) { return false; }
      SyntaxToken that = (SyntaxToken) o;
      return Objects.equals(start, that.start) && Objects.equals(end, that.end) && Objects.equals(color, that.color);
    }

    @Override
    public int hashCode() {
      return Objects.hash(start, end, color);
    }

    public static final class Builder {

      private @Nullable Long start;

      @CanIgnoreReturnValue
      public @NonNull Builder setStart(@Nullable Long setterArg) {
        this.start = setterArg;
        return this;
      }

      private @Nullable Long end;

      @CanIgnoreReturnValue
      public @NonNull Builder setEnd(@Nullable Long setterArg) {
        this.end = setterArg;
        return this;
      }

      private @Nullable Long color;

      @CanIgnoreReturnValue
      public @NonNull Builder setColor(@Nullable Long setterArg) {
        this.color = setterArg;
        return this;
      }

      public @NonNull SyntaxToken build() {
        SyntaxToken pigeonReturn = new SyntaxToken();
        pigeonReturn.setStart(start);
        pigeonReturn.setEnd(end);
        pigeonReturn.setColor(color);
        return pigeonReturn;
      }
    }

    @NonNull
    ArrayList<Object> toList() {
      ArrayList<Object> toListResult = new ArrayList<>(3);
      toListResult.add(start);
      toListResult.add(end);
      toListResult.add(color);
      return toListResult;
    }

    static @NonNull SyntaxToken fromList(@NonNull ArrayList<Object> pigeonVar_list) {
      SyntaxToken pigeonResult = new SyntaxToken();
      Object start = pigeonVar_list.get(0);
      pigeonResult.setStart((Long) start);
      Object end = pigeonVar_list.get(1);
      pigeonResult.setEnd((Long) end);
      Object color = pigeonVar_list.get(2);
      pigeonResult.setColor((Long) color);
      return pigeonResult;
    }
  }

  /** Generated class from Pigeon that represents data sent in messages. */
  public static final class SnippetLanguage {
    private @Nullable String raw;

    public @Nullable String getRaw() {
      return raw;
    }

    public void setRaw(@Nullable String setterArg) {
      this.raw = setterArg;
    }

    private @Nullable SnippetLanguageType type;

    public @Nullable SnippetLanguageType getType() {
      return type;
    }

    public void setType(@Nullable SnippetLanguageType setterArg) {
      this.type = setterArg;
    }

    @Override
    public boolean equals(Object o) {
      if (this == o) { return true; }
      if (o == null || getClass() != o.getClass()) { return false; }
      SnippetLanguage that = (SnippetLanguage) o;
      return Objects.equals(raw, that.raw) && Objects.equals(type, that.type);
    }

    @Override
    public int hashCode() {
      return Objects.hash(raw, type);
    }

    public static final class Builder {

      private @Nullable String raw;

      @CanIgnoreReturnValue
      public @NonNull Builder setRaw(@Nullable String setterArg) {
        this.raw = setterArg;
        return this;
      }

      private @Nullable SnippetLanguageType type;

      @CanIgnoreReturnValue
      public @NonNull Builder setType(@Nullable SnippetLanguageType setterArg) {
        this.type = setterArg;
        return this;
      }

      public @NonNull SnippetLanguage build() {
        SnippetLanguage pigeonReturn = new SnippetLanguage();
        pigeonReturn.setRaw(raw);
        pigeonReturn.setType(type);
        return pigeonReturn;
      }
    }

    @NonNull
    ArrayList<Object> toList() {
      ArrayList<Object> toListResult = new ArrayList<>(2);
      toListResult.add(raw);
      toListResult.add(type);
      return toListResult;
    }

    static @NonNull SnippetLanguage fromList(@NonNull ArrayList<Object> pigeonVar_list) {
      SnippetLanguage pigeonResult = new SnippetLanguage();
      Object raw = pigeonVar_list.get(0);
      pigeonResult.setRaw((String) raw);
      Object type = pigeonVar_list.get(1);
      pigeonResult.setType((SnippetLanguageType) type);
      return pigeonResult;
    }
  }

  /** Generated class from Pigeon that represents data sent in messages. */
  public static final class Owner {
    private @Nullable Long id;

    public @Nullable Long getId() {
      return id;
    }

    public void setId(@Nullable Long setterArg) {
      this.id = setterArg;
    }

    private @Nullable String login;

    public @Nullable String getLogin() {
      return login;
    }

    public void setLogin(@Nullable String setterArg) {
      this.login = setterArg;
    }

    @Override
    public boolean equals(Object o) {
      if (this == o) { return true; }
      if (o == null || getClass() != o.getClass()) { return false; }
      Owner that = (Owner) o;
      return Objects.equals(id, that.id) && Objects.equals(login, that.login);
    }

    @Override
    public int hashCode() {
      return Objects.hash(id, login);
    }

    public static final class Builder {

      private @Nullable Long id;

      @CanIgnoreReturnValue
      public @NonNull Builder setId(@Nullable Long setterArg) {
        this.id = setterArg;
        return this;
      }

      private @Nullable String login;

      @CanIgnoreReturnValue
      public @NonNull Builder setLogin(@Nullable String setterArg) {
        this.login = setterArg;
        return this;
      }

      public @NonNull Owner build() {
        Owner pigeonReturn = new Owner();
        pigeonReturn.setId(id);
        pigeonReturn.setLogin(login);
        return pigeonReturn;
      }
    }

    @NonNull
    ArrayList<Object> toList() {
      ArrayList<Object> toListResult = new ArrayList<>(2);
      toListResult.add(id);
      toListResult.add(login);
      return toListResult;
    }

    static @NonNull Owner fromList(@NonNull ArrayList<Object> pigeonVar_list) {
      Owner pigeonResult = new Owner();
      Object id = pigeonVar_list.get(0);
      pigeonResult.setId((Long) id);
      Object login = pigeonVar_list.get(1);
      pigeonResult.setLogin((String) login);
      return pigeonResult;
    }
  }

  /** Generated class from Pigeon that represents data sent in messages. */
  public static final class SnippetFilter {
    private @Nullable List<String> languages;

    public @Nullable List<String> getLanguages() {
      return languages;
    }

    public void setLanguages(@Nullable List<String> setterArg) {
      this.languages = setterArg;
    }

    private @Nullable List<String> selectedLanguages;

    public @Nullable List<String> getSelectedLanguages() {
      return selectedLanguages;
    }

    public void setSelectedLanguages(@Nullable List<String> setterArg) {
      this.selectedLanguages = setterArg;
    }

    private @Nullable List<String> scopes;

    public @Nullable List<String> getScopes() {
      return scopes;
    }

    public void setScopes(@Nullable List<String> setterArg) {
      this.scopes = setterArg;
    }

    private @Nullable String selectedScope;

    public @Nullable String getSelectedScope() {
      return selectedScope;
    }

    public void setSelectedScope(@Nullable String setterArg) {
      this.selectedScope = setterArg;
    }

    @Override
    public boolean equals(Object o) {
      if (this == o) { return true; }
      if (o == null || getClass() != o.getClass()) { return false; }
      SnippetFilter that = (SnippetFilter) o;
      return Objects.equals(languages, that.languages) && Objects.equals(selectedLanguages, that.selectedLanguages) && Objects.equals(scopes, that.scopes) && Objects.equals(selectedScope, that.selectedScope);
    }

    @Override
    public int hashCode() {
      return Objects.hash(languages, selectedLanguages, scopes, selectedScope);
    }

    public static final class Builder {

      private @Nullable List<String> languages;

      @CanIgnoreReturnValue
      public @NonNull Builder setLanguages(@Nullable List<String> setterArg) {
        this.languages = setterArg;
        return this;
      }

      private @Nullable List<String> selectedLanguages;

      @CanIgnoreReturnValue
      public @NonNull Builder setSelectedLanguages(@Nullable List<String> setterArg) {
        this.selectedLanguages = setterArg;
        return this;
      }

      private @Nullable List<String> scopes;

      @CanIgnoreReturnValue
      public @NonNull Builder setScopes(@Nullable List<String> setterArg) {
        this.scopes = setterArg;
        return this;
      }

      private @Nullable String selectedScope;

      @CanIgnoreReturnValue
      public @NonNull Builder setSelectedScope(@Nullable String setterArg) {
        this.selectedScope = setterArg;
        return this;
      }

      public @NonNull SnippetFilter build() {
        SnippetFilter pigeonReturn = new SnippetFilter();
        pigeonReturn.setLanguages(languages);
        pigeonReturn.setSelectedLanguages(selectedLanguages);
        pigeonReturn.setScopes(scopes);
        pigeonReturn.setSelectedScope(selectedScope);
        return pigeonReturn;
      }
    }

    @NonNull
    ArrayList<Object> toList() {
      ArrayList<Object> toListResult = new ArrayList<>(4);
      toListResult.add(languages);
      toListResult.add(selectedLanguages);
      toListResult.add(scopes);
      toListResult.add(selectedScope);
      return toListResult;
    }

    static @NonNull SnippetFilter fromList(@NonNull ArrayList<Object> pigeonVar_list) {
      SnippetFilter pigeonResult = new SnippetFilter();
      Object languages = pigeonVar_list.get(0);
      pigeonResult.setLanguages((List<String>) languages);
      Object selectedLanguages = pigeonVar_list.get(1);
      pigeonResult.setSelectedLanguages((List<String>) selectedLanguages);
      Object scopes = pigeonVar_list.get(2);
      pigeonResult.setScopes((List<String>) scopes);
      Object selectedScope = pigeonVar_list.get(3);
      pigeonResult.setSelectedScope((String) selectedScope);
      return pigeonResult;
    }
  }

  /** Generated class from Pigeon that represents data sent in messages. */
  public static final class MainModelStateData {
    private @Nullable ModelState state;

    public @Nullable ModelState getState() {
      return state;
    }

    public void setState(@Nullable ModelState setterArg) {
      this.state = setterArg;
    }

    private @Nullable Boolean isLoading;

    public @Nullable Boolean getIsLoading() {
      return isLoading;
    }

    public void setIsLoading(@Nullable Boolean setterArg) {
      this.isLoading = setterArg;
    }

    private @Nullable List<Snippet> data;

    public @Nullable List<Snippet> getData() {
      return data;
    }

    public void setData(@Nullable List<Snippet> setterArg) {
      this.data = setterArg;
    }

    private @Nullable SnippetFilter filter;

    public @Nullable SnippetFilter getFilter() {
      return filter;
    }

    public void setFilter(@Nullable SnippetFilter setterArg) {
      this.filter = setterArg;
    }

    private @Nullable String error;

    public @Nullable String getError() {
      return error;
    }

    public void setError(@Nullable String setterArg) {
      this.error = setterArg;
    }

    private @Nullable Long oldHash;

    public @Nullable Long getOldHash() {
      return oldHash;
    }

    public void setOldHash(@Nullable Long setterArg) {
      this.oldHash = setterArg;
    }

    private @Nullable Long newHash;

    public @Nullable Long getNewHash() {
      return newHash;
    }

    public void setNewHash(@Nullable Long setterArg) {
      this.newHash = setterArg;
    }

    @Override
    public boolean equals(Object o) {
      if (this == o) { return true; }
      if (o == null || getClass() != o.getClass()) { return false; }
      MainModelStateData that = (MainModelStateData) o;
      return Objects.equals(state, that.state) && Objects.equals(isLoading, that.isLoading) && Objects.equals(data, that.data) && Objects.equals(filter, that.filter) && Objects.equals(error, that.error) && Objects.equals(oldHash, that.oldHash) && Objects.equals(newHash, that.newHash);
    }

    @Override
    public int hashCode() {
      return Objects.hash(state, isLoading, data, filter, error, oldHash, newHash);
    }

    public static final class Builder {

      private @Nullable ModelState state;

      @CanIgnoreReturnValue
      public @NonNull Builder setState(@Nullable ModelState setterArg) {
        this.state = setterArg;
        return this;
      }

      private @Nullable Boolean isLoading;

      @CanIgnoreReturnValue
      public @NonNull Builder setIsLoading(@Nullable Boolean setterArg) {
        this.isLoading = setterArg;
        return this;
      }

      private @Nullable List<Snippet> data;

      @CanIgnoreReturnValue
      public @NonNull Builder setData(@Nullable List<Snippet> setterArg) {
        this.data = setterArg;
        return this;
      }

      private @Nullable SnippetFilter filter;

      @CanIgnoreReturnValue
      public @NonNull Builder setFilter(@Nullable SnippetFilter setterArg) {
        this.filter = setterArg;
        return this;
      }

      private @Nullable String error;

      @CanIgnoreReturnValue
      public @NonNull Builder setError(@Nullable String setterArg) {
        this.error = setterArg;
        return this;
      }

      private @Nullable Long oldHash;

      @CanIgnoreReturnValue
      public @NonNull Builder setOldHash(@Nullable Long setterArg) {
        this.oldHash = setterArg;
        return this;
      }

      private @Nullable Long newHash;

      @CanIgnoreReturnValue
      public @NonNull Builder setNewHash(@Nullable Long setterArg) {
        this.newHash = setterArg;
        return this;
      }

      public @NonNull MainModelStateData build() {
        MainModelStateData pigeonReturn = new MainModelStateData();
        pigeonReturn.setState(state);
        pigeonReturn.setIsLoading(isLoading);
        pigeonReturn.setData(data);
        pigeonReturn.setFilter(filter);
        pigeonReturn.setError(error);
        pigeonReturn.setOldHash(oldHash);
        pigeonReturn.setNewHash(newHash);
        return pigeonReturn;
      }
    }

    @NonNull
    ArrayList<Object> toList() {
      ArrayList<Object> toListResult = new ArrayList<>(7);
      toListResult.add(state);
      toListResult.add(isLoading);
      toListResult.add(data);
      toListResult.add(filter);
      toListResult.add(error);
      toListResult.add(oldHash);
      toListResult.add(newHash);
      return toListResult;
    }

    static @NonNull MainModelStateData fromList(@NonNull ArrayList<Object> pigeonVar_list) {
      MainModelStateData pigeonResult = new MainModelStateData();
      Object state = pigeonVar_list.get(0);
      pigeonResult.setState((ModelState) state);
      Object isLoading = pigeonVar_list.get(1);
      pigeonResult.setIsLoading((Boolean) isLoading);
      Object data = pigeonVar_list.get(2);
      pigeonResult.setData((List<Snippet>) data);
      Object filter = pigeonVar_list.get(3);
      pigeonResult.setFilter((SnippetFilter) filter);
      Object error = pigeonVar_list.get(4);
      pigeonResult.setError((String) error);
      Object oldHash = pigeonVar_list.get(5);
      pigeonResult.setOldHash((Long) oldHash);
      Object newHash = pigeonVar_list.get(6);
      pigeonResult.setNewHash((Long) newHash);
      return pigeonResult;
    }
  }

  /** Generated class from Pigeon that represents data sent in messages. */
  public static final class MainModelEventData {
    private @Nullable MainModelEvent event;

    public @Nullable MainModelEvent getEvent() {
      return event;
    }

    public void setEvent(@Nullable MainModelEvent setterArg) {
      this.event = setterArg;
    }

    private @Nullable String message;

    public @Nullable String getMessage() {
      return message;
    }

    public void setMessage(@Nullable String setterArg) {
      this.message = setterArg;
    }

    private @Nullable Long oldHash;

    public @Nullable Long getOldHash() {
      return oldHash;
    }

    public void setOldHash(@Nullable Long setterArg) {
      this.oldHash = setterArg;
    }

    private @Nullable Long newHash;

    public @Nullable Long getNewHash() {
      return newHash;
    }

    public void setNewHash(@Nullable Long setterArg) {
      this.newHash = setterArg;
    }

    @Override
    public boolean equals(Object o) {
      if (this == o) { return true; }
      if (o == null || getClass() != o.getClass()) { return false; }
      MainModelEventData that = (MainModelEventData) o;
      return Objects.equals(event, that.event) && Objects.equals(message, that.message) && Objects.equals(oldHash, that.oldHash) && Objects.equals(newHash, that.newHash);
    }

    @Override
    public int hashCode() {
      return Objects.hash(event, message, oldHash, newHash);
    }

    public static final class Builder {

      private @Nullable MainModelEvent event;

      @CanIgnoreReturnValue
      public @NonNull Builder setEvent(@Nullable MainModelEvent setterArg) {
        this.event = setterArg;
        return this;
      }

      private @Nullable String message;

      @CanIgnoreReturnValue
      public @NonNull Builder setMessage(@Nullable String setterArg) {
        this.message = setterArg;
        return this;
      }

      private @Nullable Long oldHash;

      @CanIgnoreReturnValue
      public @NonNull Builder setOldHash(@Nullable Long setterArg) {
        this.oldHash = setterArg;
        return this;
      }

      private @Nullable Long newHash;

      @CanIgnoreReturnValue
      public @NonNull Builder setNewHash(@Nullable Long setterArg) {
        this.newHash = setterArg;
        return this;
      }

      public @NonNull MainModelEventData build() {
        MainModelEventData pigeonReturn = new MainModelEventData();
        pigeonReturn.setEvent(event);
        pigeonReturn.setMessage(message);
        pigeonReturn.setOldHash(oldHash);
        pigeonReturn.setNewHash(newHash);
        return pigeonReturn;
      }
    }

    @NonNull
    ArrayList<Object> toList() {
      ArrayList<Object> toListResult = new ArrayList<>(4);
      toListResult.add(event);
      toListResult.add(message);
      toListResult.add(oldHash);
      toListResult.add(newHash);
      return toListResult;
    }

    static @NonNull MainModelEventData fromList(@NonNull ArrayList<Object> pigeonVar_list) {
      MainModelEventData pigeonResult = new MainModelEventData();
      Object event = pigeonVar_list.get(0);
      pigeonResult.setEvent((MainModelEvent) event);
      Object message = pigeonVar_list.get(1);
      pigeonResult.setMessage((String) message);
      Object oldHash = pigeonVar_list.get(2);
      pigeonResult.setOldHash((Long) oldHash);
      Object newHash = pigeonVar_list.get(3);
      pigeonResult.setNewHash((Long) newHash);
      return pigeonResult;
    }
  }

  /** Generated class from Pigeon that represents data sent in messages. */
  public static final class DetailModelStateData {
    private @Nullable ModelState state;

    public @Nullable ModelState getState() {
      return state;
    }

    public void setState(@Nullable ModelState setterArg) {
      this.state = setterArg;
    }

    private @Nullable Boolean isLoading;

    public @Nullable Boolean getIsLoading() {
      return isLoading;
    }

    public void setIsLoading(@Nullable Boolean setterArg) {
      this.isLoading = setterArg;
    }

    private @Nullable Snippet data;

    public @Nullable Snippet getData() {
      return data;
    }

    public void setData(@Nullable Snippet setterArg) {
      this.data = setterArg;
    }

    private @Nullable String error;

    public @Nullable String getError() {
      return error;
    }

    public void setError(@Nullable String setterArg) {
      this.error = setterArg;
    }

    private @Nullable Long oldHash;

    public @Nullable Long getOldHash() {
      return oldHash;
    }

    public void setOldHash(@Nullable Long setterArg) {
      this.oldHash = setterArg;
    }

    private @Nullable Long newHash;

    public @Nullable Long getNewHash() {
      return newHash;
    }

    public void setNewHash(@Nullable Long setterArg) {
      this.newHash = setterArg;
    }

    @Override
    public boolean equals(Object o) {
      if (this == o) { return true; }
      if (o == null || getClass() != o.getClass()) { return false; }
      DetailModelStateData that = (DetailModelStateData) o;
      return Objects.equals(state, that.state) && Objects.equals(isLoading, that.isLoading) && Objects.equals(data, that.data) && Objects.equals(error, that.error) && Objects.equals(oldHash, that.oldHash) && Objects.equals(newHash, that.newHash);
    }

    @Override
    public int hashCode() {
      return Objects.hash(state, isLoading, data, error, oldHash, newHash);
    }

    public static final class Builder {

      private @Nullable ModelState state;

      @CanIgnoreReturnValue
      public @NonNull Builder setState(@Nullable ModelState setterArg) {
        this.state = setterArg;
        return this;
      }

      private @Nullable Boolean isLoading;

      @CanIgnoreReturnValue
      public @NonNull Builder setIsLoading(@Nullable Boolean setterArg) {
        this.isLoading = setterArg;
        return this;
      }

      private @Nullable Snippet data;

      @CanIgnoreReturnValue
      public @NonNull Builder setData(@Nullable Snippet setterArg) {
        this.data = setterArg;
        return this;
      }

      private @Nullable String error;

      @CanIgnoreReturnValue
      public @NonNull Builder setError(@Nullable String setterArg) {
        this.error = setterArg;
        return this;
      }

      private @Nullable Long oldHash;

      @CanIgnoreReturnValue
      public @NonNull Builder setOldHash(@Nullable Long setterArg) {
        this.oldHash = setterArg;
        return this;
      }

      private @Nullable Long newHash;

      @CanIgnoreReturnValue
      public @NonNull Builder setNewHash(@Nullable Long setterArg) {
        this.newHash = setterArg;
        return this;
      }

      public @NonNull DetailModelStateData build() {
        DetailModelStateData pigeonReturn = new DetailModelStateData();
        pigeonReturn.setState(state);
        pigeonReturn.setIsLoading(isLoading);
        pigeonReturn.setData(data);
        pigeonReturn.setError(error);
        pigeonReturn.setOldHash(oldHash);
        pigeonReturn.setNewHash(newHash);
        return pigeonReturn;
      }
    }

    @NonNull
    ArrayList<Object> toList() {
      ArrayList<Object> toListResult = new ArrayList<>(6);
      toListResult.add(state);
      toListResult.add(isLoading);
      toListResult.add(data);
      toListResult.add(error);
      toListResult.add(oldHash);
      toListResult.add(newHash);
      return toListResult;
    }

    static @NonNull DetailModelStateData fromList(@NonNull ArrayList<Object> pigeonVar_list) {
      DetailModelStateData pigeonResult = new DetailModelStateData();
      Object state = pigeonVar_list.get(0);
      pigeonResult.setState((ModelState) state);
      Object isLoading = pigeonVar_list.get(1);
      pigeonResult.setIsLoading((Boolean) isLoading);
      Object data = pigeonVar_list.get(2);
      pigeonResult.setData((Snippet) data);
      Object error = pigeonVar_list.get(3);
      pigeonResult.setError((String) error);
      Object oldHash = pigeonVar_list.get(4);
      pigeonResult.setOldHash((Long) oldHash);
      Object newHash = pigeonVar_list.get(5);
      pigeonResult.setNewHash((Long) newHash);
      return pigeonResult;
    }
  }

  /** Generated class from Pigeon that represents data sent in messages. */
  public static final class DetailModelEventData {
    private @Nullable DetailModelEvent event;

    public @Nullable DetailModelEvent getEvent() {
      return event;
    }

    public void setEvent(@Nullable DetailModelEvent setterArg) {
      this.event = setterArg;
    }

    private @Nullable String value;

    public @Nullable String getValue() {
      return value;
    }

    public void setValue(@Nullable String setterArg) {
      this.value = setterArg;
    }

    private @Nullable Long oldHash;

    public @Nullable Long getOldHash() {
      return oldHash;
    }

    public void setOldHash(@Nullable Long setterArg) {
      this.oldHash = setterArg;
    }

    private @Nullable Long newHash;

    public @Nullable Long getNewHash() {
      return newHash;
    }

    public void setNewHash(@Nullable Long setterArg) {
      this.newHash = setterArg;
    }

    @Override
    public boolean equals(Object o) {
      if (this == o) { return true; }
      if (o == null || getClass() != o.getClass()) { return false; }
      DetailModelEventData that = (DetailModelEventData) o;
      return Objects.equals(event, that.event) && Objects.equals(value, that.value) && Objects.equals(oldHash, that.oldHash) && Objects.equals(newHash, that.newHash);
    }

    @Override
    public int hashCode() {
      return Objects.hash(event, value, oldHash, newHash);
    }

    public static final class Builder {

      private @Nullable DetailModelEvent event;

      @CanIgnoreReturnValue
      public @NonNull Builder setEvent(@Nullable DetailModelEvent setterArg) {
        this.event = setterArg;
        return this;
      }

      private @Nullable String value;

      @CanIgnoreReturnValue
      public @NonNull Builder setValue(@Nullable String setterArg) {
        this.value = setterArg;
        return this;
      }

      private @Nullable Long oldHash;

      @CanIgnoreReturnValue
      public @NonNull Builder setOldHash(@Nullable Long setterArg) {
        this.oldHash = setterArg;
        return this;
      }

      private @Nullable Long newHash;

      @CanIgnoreReturnValue
      public @NonNull Builder setNewHash(@Nullable Long setterArg) {
        this.newHash = setterArg;
        return this;
      }

      public @NonNull DetailModelEventData build() {
        DetailModelEventData pigeonReturn = new DetailModelEventData();
        pigeonReturn.setEvent(event);
        pigeonReturn.setValue(value);
        pigeonReturn.setOldHash(oldHash);
        pigeonReturn.setNewHash(newHash);
        return pigeonReturn;
      }
    }

    @NonNull
    ArrayList<Object> toList() {
      ArrayList<Object> toListResult = new ArrayList<>(4);
      toListResult.add(event);
      toListResult.add(value);
      toListResult.add(oldHash);
      toListResult.add(newHash);
      return toListResult;
    }

    static @NonNull DetailModelEventData fromList(@NonNull ArrayList<Object> pigeonVar_list) {
      DetailModelEventData pigeonResult = new DetailModelEventData();
      Object event = pigeonVar_list.get(0);
      pigeonResult.setEvent((DetailModelEvent) event);
      Object value = pigeonVar_list.get(1);
      pigeonResult.setValue((String) value);
      Object oldHash = pigeonVar_list.get(2);
      pigeonResult.setOldHash((Long) oldHash);
      Object newHash = pigeonVar_list.get(3);
      pigeonResult.setNewHash((Long) newHash);
      return pigeonResult;
    }
  }

  /** Generated class from Pigeon that represents data sent in messages. */
  public static final class LoginModelStateData {
    private @Nullable ModelState state;

    public @Nullable ModelState getState() {
      return state;
    }

    public void setState(@Nullable ModelState setterArg) {
      this.state = setterArg;
    }

    private @Nullable Boolean isLoading;

    public @Nullable Boolean getIsLoading() {
      return isLoading;
    }

    public void setIsLoading(@Nullable Boolean setterArg) {
      this.isLoading = setterArg;
    }

    private @Nullable Long oldHash;

    public @Nullable Long getOldHash() {
      return oldHash;
    }

    public void setOldHash(@Nullable Long setterArg) {
      this.oldHash = setterArg;
    }

    private @Nullable Long newHash;

    public @Nullable Long getNewHash() {
      return newHash;
    }

    public void setNewHash(@Nullable Long setterArg) {
      this.newHash = setterArg;
    }

    @Override
    public boolean equals(Object o) {
      if (this == o) { return true; }
      if (o == null || getClass() != o.getClass()) { return false; }
      LoginModelStateData that = (LoginModelStateData) o;
      return Objects.equals(state, that.state) && Objects.equals(isLoading, that.isLoading) && Objects.equals(oldHash, that.oldHash) && Objects.equals(newHash, that.newHash);
    }

    @Override
    public int hashCode() {
      return Objects.hash(state, isLoading, oldHash, newHash);
    }

    public static final class Builder {

      private @Nullable ModelState state;

      @CanIgnoreReturnValue
      public @NonNull Builder setState(@Nullable ModelState setterArg) {
        this.state = setterArg;
        return this;
      }

      private @Nullable Boolean isLoading;

      @CanIgnoreReturnValue
      public @NonNull Builder setIsLoading(@Nullable Boolean setterArg) {
        this.isLoading = setterArg;
        return this;
      }

      private @Nullable Long oldHash;

      @CanIgnoreReturnValue
      public @NonNull Builder setOldHash(@Nullable Long setterArg) {
        this.oldHash = setterArg;
        return this;
      }

      private @Nullable Long newHash;

      @CanIgnoreReturnValue
      public @NonNull Builder setNewHash(@Nullable Long setterArg) {
        this.newHash = setterArg;
        return this;
      }

      public @NonNull LoginModelStateData build() {
        LoginModelStateData pigeonReturn = new LoginModelStateData();
        pigeonReturn.setState(state);
        pigeonReturn.setIsLoading(isLoading);
        pigeonReturn.setOldHash(oldHash);
        pigeonReturn.setNewHash(newHash);
        return pigeonReturn;
      }
    }

    @NonNull
    ArrayList<Object> toList() {
      ArrayList<Object> toListResult = new ArrayList<>(4);
      toListResult.add(state);
      toListResult.add(isLoading);
      toListResult.add(oldHash);
      toListResult.add(newHash);
      return toListResult;
    }

    static @NonNull LoginModelStateData fromList(@NonNull ArrayList<Object> pigeonVar_list) {
      LoginModelStateData pigeonResult = new LoginModelStateData();
      Object state = pigeonVar_list.get(0);
      pigeonResult.setState((ModelState) state);
      Object isLoading = pigeonVar_list.get(1);
      pigeonResult.setIsLoading((Boolean) isLoading);
      Object oldHash = pigeonVar_list.get(2);
      pigeonResult.setOldHash((Long) oldHash);
      Object newHash = pigeonVar_list.get(3);
      pigeonResult.setNewHash((Long) newHash);
      return pigeonResult;
    }
  }

  /** Generated class from Pigeon that represents data sent in messages. */
  public static final class LoginModelEventData {
    private @Nullable LoginModelEvent event;

    public @Nullable LoginModelEvent getEvent() {
      return event;
    }

    public void setEvent(@Nullable LoginModelEvent setterArg) {
      this.event = setterArg;
    }

    private @Nullable Long oldHash;

    public @Nullable Long getOldHash() {
      return oldHash;
    }

    public void setOldHash(@Nullable Long setterArg) {
      this.oldHash = setterArg;
    }

    private @Nullable Long newHash;

    public @Nullable Long getNewHash() {
      return newHash;
    }

    public void setNewHash(@Nullable Long setterArg) {
      this.newHash = setterArg;
    }

    @Override
    public boolean equals(Object o) {
      if (this == o) { return true; }
      if (o == null || getClass() != o.getClass()) { return false; }
      LoginModelEventData that = (LoginModelEventData) o;
      return Objects.equals(event, that.event) && Objects.equals(oldHash, that.oldHash) && Objects.equals(newHash, that.newHash);
    }

    @Override
    public int hashCode() {
      return Objects.hash(event, oldHash, newHash);
    }

    public static final class Builder {

      private @Nullable LoginModelEvent event;

      @CanIgnoreReturnValue
      public @NonNull Builder setEvent(@Nullable LoginModelEvent setterArg) {
        this.event = setterArg;
        return this;
      }

      private @Nullable Long oldHash;

      @CanIgnoreReturnValue
      public @NonNull Builder setOldHash(@Nullable Long setterArg) {
        this.oldHash = setterArg;
        return this;
      }

      private @Nullable Long newHash;

      @CanIgnoreReturnValue
      public @NonNull Builder setNewHash(@Nullable Long setterArg) {
        this.newHash = setterArg;
        return this;
      }

      public @NonNull LoginModelEventData build() {
        LoginModelEventData pigeonReturn = new LoginModelEventData();
        pigeonReturn.setEvent(event);
        pigeonReturn.setOldHash(oldHash);
        pigeonReturn.setNewHash(newHash);
        return pigeonReturn;
      }
    }

    @NonNull
    ArrayList<Object> toList() {
      ArrayList<Object> toListResult = new ArrayList<>(3);
      toListResult.add(event);
      toListResult.add(oldHash);
      toListResult.add(newHash);
      return toListResult;
    }

    static @NonNull LoginModelEventData fromList(@NonNull ArrayList<Object> pigeonVar_list) {
      LoginModelEventData pigeonResult = new LoginModelEventData();
      Object event = pigeonVar_list.get(0);
      pigeonResult.setEvent((LoginModelEvent) event);
      Object oldHash = pigeonVar_list.get(1);
      pigeonResult.setOldHash((Long) oldHash);
      Object newHash = pigeonVar_list.get(2);
      pigeonResult.setNewHash((Long) newHash);
      return pigeonResult;
    }
  }

  private static class PigeonCodec extends StandardMessageCodec {
    public static final PigeonCodec INSTANCE = new PigeonCodec();

    private PigeonCodec() {}

    @Override
    protected Object readValueOfType(byte type, @NonNull ByteBuffer buffer) {
      switch (type) {
        case (byte) 129: {
          Object value = readValue(buffer);
          return value == null ? null : SnippetLanguageType.values()[((Long) value).intValue()];
        }
        case (byte) 130: {
          Object value = readValue(buffer);
          return value == null ? null : SnippetFilterType.values()[((Long) value).intValue()];
        }
        case (byte) 131: {
          Object value = readValue(buffer);
          return value == null ? null : UserReaction.values()[((Long) value).intValue()];
        }
        case (byte) 132: {
          Object value = readValue(buffer);
          return value == null ? null : ModelState.values()[((Long) value).intValue()];
        }
        case (byte) 133: {
          Object value = readValue(buffer);
          return value == null ? null : MainModelEvent.values()[((Long) value).intValue()];
        }
        case (byte) 134: {
          Object value = readValue(buffer);
          return value == null ? null : DetailModelEvent.values()[((Long) value).intValue()];
        }
        case (byte) 135: {
          Object value = readValue(buffer);
          return value == null ? null : LoginModelEvent.values()[((Long) value).intValue()];
        }
        case (byte) 136:
          return Snippet.fromList((ArrayList<Object>) readValue(buffer));
        case (byte) 137:
          return SnippetCode.fromList((ArrayList<Object>) readValue(buffer));
        case (byte) 138:
          return SyntaxToken.fromList((ArrayList<Object>) readValue(buffer));
        case (byte) 139:
          return SnippetLanguage.fromList((ArrayList<Object>) readValue(buffer));
        case (byte) 140:
          return Owner.fromList((ArrayList<Object>) readValue(buffer));
        case (byte) 141:
          return SnippetFilter.fromList((ArrayList<Object>) readValue(buffer));
        case (byte) 142:
          return MainModelStateData.fromList((ArrayList<Object>) readValue(buffer));
        case (byte) 143:
          return MainModelEventData.fromList((ArrayList<Object>) readValue(buffer));
        case (byte) 144:
          return DetailModelStateData.fromList((ArrayList<Object>) readValue(buffer));
        case (byte) 145:
          return DetailModelEventData.fromList((ArrayList<Object>) readValue(buffer));
        case (byte) 146:
          return LoginModelStateData.fromList((ArrayList<Object>) readValue(buffer));
        case (byte) 147:
          return LoginModelEventData.fromList((ArrayList<Object>) readValue(buffer));
        default:
          return super.readValueOfType(type, buffer);
      }
    }

    @Override
    protected void writeValue(@NonNull ByteArrayOutputStream stream, Object value) {
      if (value instanceof SnippetLanguageType) {
        stream.write(129);
        writeValue(stream, value == null ? null : ((SnippetLanguageType) value).index);
      } else if (value instanceof SnippetFilterType) {
        stream.write(130);
        writeValue(stream, value == null ? null : ((SnippetFilterType) value).index);
      } else if (value instanceof UserReaction) {
        stream.write(131);
        writeValue(stream, value == null ? null : ((UserReaction) value).index);
      } else if (value instanceof ModelState) {
        stream.write(132);
        writeValue(stream, value == null ? null : ((ModelState) value).index);
      } else if (value instanceof MainModelEvent) {
        stream.write(133);
        writeValue(stream, value == null ? null : ((MainModelEvent) value).index);
      } else if (value instanceof DetailModelEvent) {
        stream.write(134);
        writeValue(stream, value == null ? null : ((DetailModelEvent) value).index);
      } else if (value instanceof LoginModelEvent) {
        stream.write(135);
        writeValue(stream, value == null ? null : ((LoginModelEvent) value).index);
      } else if (value instanceof Snippet) {
        stream.write(136);
        writeValue(stream, ((Snippet) value).toList());
      } else if (value instanceof SnippetCode) {
        stream.write(137);
        writeValue(stream, ((SnippetCode) value).toList());
      } else if (value instanceof SyntaxToken) {
        stream.write(138);
        writeValue(stream, ((SyntaxToken) value).toList());
      } else if (value instanceof SnippetLanguage) {
        stream.write(139);
        writeValue(stream, ((SnippetLanguage) value).toList());
      } else if (value instanceof Owner) {
        stream.write(140);
        writeValue(stream, ((Owner) value).toList());
      } else if (value instanceof SnippetFilter) {
        stream.write(141);
        writeValue(stream, ((SnippetFilter) value).toList());
      } else if (value instanceof MainModelStateData) {
        stream.write(142);
        writeValue(stream, ((MainModelStateData) value).toList());
      } else if (value instanceof MainModelEventData) {
        stream.write(143);
        writeValue(stream, ((MainModelEventData) value).toList());
      } else if (value instanceof DetailModelStateData) {
        stream.write(144);
        writeValue(stream, ((DetailModelStateData) value).toList());
      } else if (value instanceof DetailModelEventData) {
        stream.write(145);
        writeValue(stream, ((DetailModelEventData) value).toList());
      } else if (value instanceof LoginModelStateData) {
        stream.write(146);
        writeValue(stream, ((LoginModelStateData) value).toList());
      } else if (value instanceof LoginModelEventData) {
        stream.write(147);
        writeValue(stream, ((LoginModelEventData) value).toList());
      } else {
        super.writeValue(stream, value);
      }
    }
  }

  /** Generated interface from Pigeon that represents a handler of messages from Flutter. */
  public interface MainModelBridge {

    @NonNull 
    MainModelStateData getState();

    @NonNull 
    MainModelEventData getEvent();

    void resetEvent();

    void initState();

    void filterLanguage(@NonNull String language, @NonNull Boolean isSelected);

    void filterScope(@NonNull String scope);

    void logOut();

    /** The codec used by MainModelBridge. */
    static @NonNull MessageCodec<Object> getCodec() {
      return PigeonCodec.INSTANCE;
    }
    /**Sets up an instance of `MainModelBridge` to handle messages through the `binaryMessenger`. */
    static void setUp(@NonNull BinaryMessenger binaryMessenger, @Nullable MainModelBridge api) {
      setUp(binaryMessenger, "", api);
    }
    static void setUp(@NonNull BinaryMessenger binaryMessenger, @NonNull String messageChannelSuffix, @Nullable MainModelBridge api) {
      messageChannelSuffix = messageChannelSuffix.isEmpty() ? "" : "." + messageChannelSuffix;
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(
                binaryMessenger, "dev.flutter.pigeon.flutter_module.MainModelBridge.getState" + messageChannelSuffix, getCodec());
        if (api != null) {
          channel.setMessageHandler(
              (message, reply) -> {
                ArrayList<Object> wrapped = new ArrayList<>();
                try {
                  MainModelStateData output = api.getState();
                  wrapped.add(0, output);
                }
 catch (Throwable exception) {
                  wrapped = wrapError(exception);
                }
                reply.reply(wrapped);
              });
        } else {
          channel.setMessageHandler(null);
        }
      }
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(
                binaryMessenger, "dev.flutter.pigeon.flutter_module.MainModelBridge.getEvent" + messageChannelSuffix, getCodec());
        if (api != null) {
          channel.setMessageHandler(
              (message, reply) -> {
                ArrayList<Object> wrapped = new ArrayList<>();
                try {
                  MainModelEventData output = api.getEvent();
                  wrapped.add(0, output);
                }
 catch (Throwable exception) {
                  wrapped = wrapError(exception);
                }
                reply.reply(wrapped);
              });
        } else {
          channel.setMessageHandler(null);
        }
      }
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(
                binaryMessenger, "dev.flutter.pigeon.flutter_module.MainModelBridge.resetEvent" + messageChannelSuffix, getCodec());
        if (api != null) {
          channel.setMessageHandler(
              (message, reply) -> {
                ArrayList<Object> wrapped = new ArrayList<>();
                try {
                  api.resetEvent();
                  wrapped.add(0, null);
                }
 catch (Throwable exception) {
                  wrapped = wrapError(exception);
                }
                reply.reply(wrapped);
              });
        } else {
          channel.setMessageHandler(null);
        }
      }
      {
        BinaryMessenger.TaskQueue taskQueue = binaryMessenger.makeBackgroundTaskQueue();
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(
                binaryMessenger, "dev.flutter.pigeon.flutter_module.MainModelBridge.initState" + messageChannelSuffix, getCodec(), taskQueue);
        if (api != null) {
          channel.setMessageHandler(
              (message, reply) -> {
                ArrayList<Object> wrapped = new ArrayList<>();
                try {
                  api.initState();
                  wrapped.add(0, null);
                }
 catch (Throwable exception) {
                  wrapped = wrapError(exception);
                }
                reply.reply(wrapped);
              });
        } else {
          channel.setMessageHandler(null);
        }
      }
      {
        BinaryMessenger.TaskQueue taskQueue = binaryMessenger.makeBackgroundTaskQueue();
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(
                binaryMessenger, "dev.flutter.pigeon.flutter_module.MainModelBridge.filterLanguage" + messageChannelSuffix, getCodec(), taskQueue);
        if (api != null) {
          channel.setMessageHandler(
              (message, reply) -> {
                ArrayList<Object> wrapped = new ArrayList<>();
                ArrayList<Object> args = (ArrayList<Object>) message;
                String languageArg = (String) args.get(0);
                Boolean isSelectedArg = (Boolean) args.get(1);
                try {
                  api.filterLanguage(languageArg, isSelectedArg);
                  wrapped.add(0, null);
                }
 catch (Throwable exception) {
                  wrapped = wrapError(exception);
                }
                reply.reply(wrapped);
              });
        } else {
          channel.setMessageHandler(null);
        }
      }
      {
        BinaryMessenger.TaskQueue taskQueue = binaryMessenger.makeBackgroundTaskQueue();
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(
                binaryMessenger, "dev.flutter.pigeon.flutter_module.MainModelBridge.filterScope" + messageChannelSuffix, getCodec(), taskQueue);
        if (api != null) {
          channel.setMessageHandler(
              (message, reply) -> {
                ArrayList<Object> wrapped = new ArrayList<>();
                ArrayList<Object> args = (ArrayList<Object>) message;
                String scopeArg = (String) args.get(0);
                try {
                  api.filterScope(scopeArg);
                  wrapped.add(0, null);
                }
 catch (Throwable exception) {
                  wrapped = wrapError(exception);
                }
                reply.reply(wrapped);
              });
        } else {
          channel.setMessageHandler(null);
        }
      }
      {
        BinaryMessenger.TaskQueue taskQueue = binaryMessenger.makeBackgroundTaskQueue();
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(
                binaryMessenger, "dev.flutter.pigeon.flutter_module.MainModelBridge.logOut" + messageChannelSuffix, getCodec(), taskQueue);
        if (api != null) {
          channel.setMessageHandler(
              (message, reply) -> {
                ArrayList<Object> wrapped = new ArrayList<>();
                try {
                  api.logOut();
                  wrapped.add(0, null);
                }
 catch (Throwable exception) {
                  wrapped = wrapError(exception);
                }
                reply.reply(wrapped);
              });
        } else {
          channel.setMessageHandler(null);
        }
      }
    }
  }
  /** Generated interface from Pigeon that represents a handler of messages from Flutter. */
  public interface DetailModelBridge {

    @NonNull 
    DetailModelStateData getState();

    @NonNull 
    DetailModelEventData getEvent();

    void resetEvent();

    void load(@NonNull String uuid);

    void like();

    void dislike();

    void save();

    void copyToClipboard();

    void share();

    void delete();

    /** The codec used by DetailModelBridge. */
    static @NonNull MessageCodec<Object> getCodec() {
      return PigeonCodec.INSTANCE;
    }
    /**Sets up an instance of `DetailModelBridge` to handle messages through the `binaryMessenger`. */
    static void setUp(@NonNull BinaryMessenger binaryMessenger, @Nullable DetailModelBridge api) {
      setUp(binaryMessenger, "", api);
    }
    static void setUp(@NonNull BinaryMessenger binaryMessenger, @NonNull String messageChannelSuffix, @Nullable DetailModelBridge api) {
      messageChannelSuffix = messageChannelSuffix.isEmpty() ? "" : "." + messageChannelSuffix;
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(
                binaryMessenger, "dev.flutter.pigeon.flutter_module.DetailModelBridge.getState" + messageChannelSuffix, getCodec());
        if (api != null) {
          channel.setMessageHandler(
              (message, reply) -> {
                ArrayList<Object> wrapped = new ArrayList<>();
                try {
                  DetailModelStateData output = api.getState();
                  wrapped.add(0, output);
                }
 catch (Throwable exception) {
                  wrapped = wrapError(exception);
                }
                reply.reply(wrapped);
              });
        } else {
          channel.setMessageHandler(null);
        }
      }
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(
                binaryMessenger, "dev.flutter.pigeon.flutter_module.DetailModelBridge.getEvent" + messageChannelSuffix, getCodec());
        if (api != null) {
          channel.setMessageHandler(
              (message, reply) -> {
                ArrayList<Object> wrapped = new ArrayList<>();
                try {
                  DetailModelEventData output = api.getEvent();
                  wrapped.add(0, output);
                }
 catch (Throwable exception) {
                  wrapped = wrapError(exception);
                }
                reply.reply(wrapped);
              });
        } else {
          channel.setMessageHandler(null);
        }
      }
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(
                binaryMessenger, "dev.flutter.pigeon.flutter_module.DetailModelBridge.resetEvent" + messageChannelSuffix, getCodec());
        if (api != null) {
          channel.setMessageHandler(
              (message, reply) -> {
                ArrayList<Object> wrapped = new ArrayList<>();
                try {
                  api.resetEvent();
                  wrapped.add(0, null);
                }
 catch (Throwable exception) {
                  wrapped = wrapError(exception);
                }
                reply.reply(wrapped);
              });
        } else {
          channel.setMessageHandler(null);
        }
      }
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(
                binaryMessenger, "dev.flutter.pigeon.flutter_module.DetailModelBridge.load" + messageChannelSuffix, getCodec());
        if (api != null) {
          channel.setMessageHandler(
              (message, reply) -> {
                ArrayList<Object> wrapped = new ArrayList<>();
                ArrayList<Object> args = (ArrayList<Object>) message;
                String uuidArg = (String) args.get(0);
                try {
                  api.load(uuidArg);
                  wrapped.add(0, null);
                }
 catch (Throwable exception) {
                  wrapped = wrapError(exception);
                }
                reply.reply(wrapped);
              });
        } else {
          channel.setMessageHandler(null);
        }
      }
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(
                binaryMessenger, "dev.flutter.pigeon.flutter_module.DetailModelBridge.like" + messageChannelSuffix, getCodec());
        if (api != null) {
          channel.setMessageHandler(
              (message, reply) -> {
                ArrayList<Object> wrapped = new ArrayList<>();
                try {
                  api.like();
                  wrapped.add(0, null);
                }
 catch (Throwable exception) {
                  wrapped = wrapError(exception);
                }
                reply.reply(wrapped);
              });
        } else {
          channel.setMessageHandler(null);
        }
      }
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(
                binaryMessenger, "dev.flutter.pigeon.flutter_module.DetailModelBridge.dislike" + messageChannelSuffix, getCodec());
        if (api != null) {
          channel.setMessageHandler(
              (message, reply) -> {
                ArrayList<Object> wrapped = new ArrayList<>();
                try {
                  api.dislike();
                  wrapped.add(0, null);
                }
 catch (Throwable exception) {
                  wrapped = wrapError(exception);
                }
                reply.reply(wrapped);
              });
        } else {
          channel.setMessageHandler(null);
        }
      }
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(
                binaryMessenger, "dev.flutter.pigeon.flutter_module.DetailModelBridge.save" + messageChannelSuffix, getCodec());
        if (api != null) {
          channel.setMessageHandler(
              (message, reply) -> {
                ArrayList<Object> wrapped = new ArrayList<>();
                try {
                  api.save();
                  wrapped.add(0, null);
                }
 catch (Throwable exception) {
                  wrapped = wrapError(exception);
                }
                reply.reply(wrapped);
              });
        } else {
          channel.setMessageHandler(null);
        }
      }
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(
                binaryMessenger, "dev.flutter.pigeon.flutter_module.DetailModelBridge.copyToClipboard" + messageChannelSuffix, getCodec());
        if (api != null) {
          channel.setMessageHandler(
              (message, reply) -> {
                ArrayList<Object> wrapped = new ArrayList<>();
                try {
                  api.copyToClipboard();
                  wrapped.add(0, null);
                }
 catch (Throwable exception) {
                  wrapped = wrapError(exception);
                }
                reply.reply(wrapped);
              });
        } else {
          channel.setMessageHandler(null);
        }
      }
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(
                binaryMessenger, "dev.flutter.pigeon.flutter_module.DetailModelBridge.share" + messageChannelSuffix, getCodec());
        if (api != null) {
          channel.setMessageHandler(
              (message, reply) -> {
                ArrayList<Object> wrapped = new ArrayList<>();
                try {
                  api.share();
                  wrapped.add(0, null);
                }
 catch (Throwable exception) {
                  wrapped = wrapError(exception);
                }
                reply.reply(wrapped);
              });
        } else {
          channel.setMessageHandler(null);
        }
      }
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(
                binaryMessenger, "dev.flutter.pigeon.flutter_module.DetailModelBridge.delete" + messageChannelSuffix, getCodec());
        if (api != null) {
          channel.setMessageHandler(
              (message, reply) -> {
                ArrayList<Object> wrapped = new ArrayList<>();
                try {
                  api.delete();
                  wrapped.add(0, null);
                }
 catch (Throwable exception) {
                  wrapped = wrapError(exception);
                }
                reply.reply(wrapped);
              });
        } else {
          channel.setMessageHandler(null);
        }
      }
    }
  }
  /** Generated interface from Pigeon that represents a handler of messages from Flutter. */
  public interface LoginModelBridge {

    @NonNull 
    LoginModelStateData getState();

    @NonNull 
    LoginModelEventData getEvent();

    void loginOrRegister(@NonNull String email, @NonNull String password);

    void checkLoginState();

    void resetEvent();

    /** The codec used by LoginModelBridge. */
    static @NonNull MessageCodec<Object> getCodec() {
      return PigeonCodec.INSTANCE;
    }
    /**Sets up an instance of `LoginModelBridge` to handle messages through the `binaryMessenger`. */
    static void setUp(@NonNull BinaryMessenger binaryMessenger, @Nullable LoginModelBridge api) {
      setUp(binaryMessenger, "", api);
    }
    static void setUp(@NonNull BinaryMessenger binaryMessenger, @NonNull String messageChannelSuffix, @Nullable LoginModelBridge api) {
      messageChannelSuffix = messageChannelSuffix.isEmpty() ? "" : "." + messageChannelSuffix;
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(
                binaryMessenger, "dev.flutter.pigeon.flutter_module.LoginModelBridge.getState" + messageChannelSuffix, getCodec());
        if (api != null) {
          channel.setMessageHandler(
              (message, reply) -> {
                ArrayList<Object> wrapped = new ArrayList<>();
                try {
                  LoginModelStateData output = api.getState();
                  wrapped.add(0, output);
                }
 catch (Throwable exception) {
                  wrapped = wrapError(exception);
                }
                reply.reply(wrapped);
              });
        } else {
          channel.setMessageHandler(null);
        }
      }
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(
                binaryMessenger, "dev.flutter.pigeon.flutter_module.LoginModelBridge.getEvent" + messageChannelSuffix, getCodec());
        if (api != null) {
          channel.setMessageHandler(
              (message, reply) -> {
                ArrayList<Object> wrapped = new ArrayList<>();
                try {
                  LoginModelEventData output = api.getEvent();
                  wrapped.add(0, output);
                }
 catch (Throwable exception) {
                  wrapped = wrapError(exception);
                }
                reply.reply(wrapped);
              });
        } else {
          channel.setMessageHandler(null);
        }
      }
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(
                binaryMessenger, "dev.flutter.pigeon.flutter_module.LoginModelBridge.loginOrRegister" + messageChannelSuffix, getCodec());
        if (api != null) {
          channel.setMessageHandler(
              (message, reply) -> {
                ArrayList<Object> wrapped = new ArrayList<>();
                ArrayList<Object> args = (ArrayList<Object>) message;
                String emailArg = (String) args.get(0);
                String passwordArg = (String) args.get(1);
                try {
                  api.loginOrRegister(emailArg, passwordArg);
                  wrapped.add(0, null);
                }
 catch (Throwable exception) {
                  wrapped = wrapError(exception);
                }
                reply.reply(wrapped);
              });
        } else {
          channel.setMessageHandler(null);
        }
      }
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(
                binaryMessenger, "dev.flutter.pigeon.flutter_module.LoginModelBridge.checkLoginState" + messageChannelSuffix, getCodec());
        if (api != null) {
          channel.setMessageHandler(
              (message, reply) -> {
                ArrayList<Object> wrapped = new ArrayList<>();
                try {
                  api.checkLoginState();
                  wrapped.add(0, null);
                }
 catch (Throwable exception) {
                  wrapped = wrapError(exception);
                }
                reply.reply(wrapped);
              });
        } else {
          channel.setMessageHandler(null);
        }
      }
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(
                binaryMessenger, "dev.flutter.pigeon.flutter_module.LoginModelBridge.resetEvent" + messageChannelSuffix, getCodec());
        if (api != null) {
          channel.setMessageHandler(
              (message, reply) -> {
                ArrayList<Object> wrapped = new ArrayList<>();
                try {
                  api.resetEvent();
                  wrapped.add(0, null);
                }
 catch (Throwable exception) {
                  wrapped = wrapError(exception);
                }
                reply.reply(wrapped);
              });
        } else {
          channel.setMessageHandler(null);
        }
      }
    }
  }
}
