name: flutter_module
description: Flutter presentation layer for SnipMe app.
version: 1.0.0+1

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.7
  flutter_hooks: ^0.20.5

dev_dependencies:
  flutter_lints: ^5.0.0
  pigeon: ^4.2.2
  build_runner: ^2.4.10

flutter:
  plugin:
    platforms:
      android:
        package: pl.tkadziolka.snipmeandroid
        pluginClass: PigeonPlugin
      ios:
        pluginClass: PigeonPlugin

  uses-material-design: true

  module:
    androidX: true
    androidPackage: pl.tkadziolka.snipmeandroid.flutter.flutter_module
    iosBundleIdentifier: pl.tkadziolka.snipmeandroid.flutter.flutterModule
