// Autogenerated from Pigeon (v24.2.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package dev.snipme.snipmeapp.channel

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer

private fun wrapResult(result: Any?): List<Any?> {
  return listOf(result)
}

private fun wrapError(exception: Throwable): List<Any?> {
  return if (exception is FlutterError) {
    listOf(
      exception.code,
      exception.message,
      exception.details
    )
  } else {
    listOf(
      exception.javaClass.simpleName,
      exception.toString(),
      "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
    )
  }
}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : Throwable()

enum class SnippetLanguageType(val raw: Int) {
  C(0),
  CPP(1),
  OBJECTIVE_C(2),
  C_SHARP(3),
  JAVA(4),
  BASH(5),
  PYTHON(6),
  PERL(7),
  RUBY(8),
  SWIFT(9),
  JAVASCRIPT(10),
  KOTLIN(11),
  COFFEESCRIPT(12),
  RUST(13),
  BASIC(14),
  CLOJURE(15),
  CSS(16),
  DART(17),
  ERLANG(18),
  GO(19),
  HASKELL(20),
  LISP(21),
  LLVM(22),
  LUA(23),
  MATLAB(24),
  ML(25),
  MUMPS(26),
  NEMERLE(27),
  PASCAL(28),
  R(29),
  RD(30),
  SCALA(31),
  SQL(32),
  TEX(33),
  VB(34),
  VHDL(35),
  TCL(36),
  XQUERY(37),
  YAML(38),
  MARKDOWN(39),
  JSON(40),
  XML(41),
  PROTO(42),
  REGEX(43),
  UNKNOWN(44);

  companion object {
    fun ofRaw(raw: Int): SnippetLanguageType? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class SnippetFilterType(val raw: Int) {
  ALL(0),
  MINE(1),
  SHARED(2);

  companion object {
    fun ofRaw(raw: Int): SnippetFilterType? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class UserReaction(val raw: Int) {
  NONE(0),
  LIKE(1),
  DISLIKE(2);

  companion object {
    fun ofRaw(raw: Int): UserReaction? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class ModelState(val raw: Int) {
  LOADING(0),
  LOADED(1),
  ERROR(2);

  companion object {
    fun ofRaw(raw: Int): ModelState? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class MainModelEvent(val raw: Int) {
  NONE(0),
  ALERT(1),
  LOGOUT(2);

  companion object {
    fun ofRaw(raw: Int): MainModelEvent? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class DetailsModelEvent(val raw: Int) {
  NONE(0),
  ALERT(1),
  DELETED(2);

  companion object {
    fun ofRaw(raw: Int): DetailsModelEvent? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class LoginModelEvent(val raw: Int) {
  NONE(0),
  LOGGED(1);

  companion object {
    fun ofRaw(raw: Int): LoginModelEvent? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class Snippet (
  val uuid: String? = null,
  val title: String? = null,
  val code: SnippetCode? = null,
  val language: SnippetLanguage? = null,
  val owner: Owner? = null,
  val isOwner: Boolean? = null,
  val timeAgo: String? = null,
  val voteResult: Long? = null,
  val userReaction: UserReaction? = null,
  val isPrivate: Boolean? = null,
  val isLiked: Boolean? = null,
  val isDisliked: Boolean? = null,
  val isSaved: Boolean? = null,
  val isToDelete: Boolean? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): Snippet {
      val uuid = pigeonVar_list[0] as String?
      val title = pigeonVar_list[1] as String?
      val code = pigeonVar_list[2] as SnippetCode?
      val language = pigeonVar_list[3] as SnippetLanguage?
      val owner = pigeonVar_list[4] as Owner?
      val isOwner = pigeonVar_list[5] as Boolean?
      val timeAgo = pigeonVar_list[6] as String?
      val voteResult = pigeonVar_list[7] as Long?
      val userReaction = pigeonVar_list[8] as UserReaction?
      val isPrivate = pigeonVar_list[9] as Boolean?
      val isLiked = pigeonVar_list[10] as Boolean?
      val isDisliked = pigeonVar_list[11] as Boolean?
      val isSaved = pigeonVar_list[12] as Boolean?
      val isToDelete = pigeonVar_list[13] as Boolean?
      return Snippet(uuid, title, code, language, owner, isOwner, timeAgo, voteResult, userReaction, isPrivate, isLiked, isDisliked, isSaved, isToDelete)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      uuid,
      title,
      code,
      language,
      owner,
      isOwner,
      timeAgo,
      voteResult,
      userReaction,
      isPrivate,
      isLiked,
      isDisliked,
      isSaved,
      isToDelete,
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class SnippetCode (
  val raw: String? = null,
  val tokens: List<SyntaxToken?>? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): SnippetCode {
      val raw = pigeonVar_list[0] as String?
      val tokens = pigeonVar_list[1] as List<SyntaxToken?>?
      return SnippetCode(raw, tokens)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      raw,
      tokens,
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class SyntaxToken (
  val start: Long? = null,
  val end: Long? = null,
  val color: Long? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): SyntaxToken {
      val start = pigeonVar_list[0] as Long?
      val end = pigeonVar_list[1] as Long?
      val color = pigeonVar_list[2] as Long?
      return SyntaxToken(start, end, color)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      start,
      end,
      color,
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class SnippetLanguage (
  val raw: String? = null,
  val type: SnippetLanguageType? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): SnippetLanguage {
      val raw = pigeonVar_list[0] as String?
      val type = pigeonVar_list[1] as SnippetLanguageType?
      return SnippetLanguage(raw, type)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      raw,
      type,
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class Owner (
  val id: Long? = null,
  val login: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): Owner {
      val id = pigeonVar_list[0] as Long?
      val login = pigeonVar_list[1] as String?
      return Owner(id, login)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      id,
      login,
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class SnippetFilter (
  val languages: List<String?>? = null,
  val selectedLanguages: List<String?>? = null,
  val scopes: List<String?>? = null,
  val selectedScope: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): SnippetFilter {
      val languages = pigeonVar_list[0] as List<String?>?
      val selectedLanguages = pigeonVar_list[1] as List<String?>?
      val scopes = pigeonVar_list[2] as List<String?>?
      val selectedScope = pigeonVar_list[3] as String?
      return SnippetFilter(languages, selectedLanguages, scopes, selectedScope)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      languages,
      selectedLanguages,
      scopes,
      selectedScope,
    )
  }
}

/**
 * Generated class from Pigeon that represents data sent in messages.
 * This class should not be extended by any user class outside of the generated file.
 */
sealed class ModelStateData 
/**
 * Generated class from Pigeon that represents data sent in messages.
 * This class should not be extended by any user class outside of the generated file.
 */
sealed class ModelEventData 
/** Generated class from Pigeon that represents data sent in messages. */
data class MainModelStateData (
  val state: ModelState? = null,
  val isLoading: Boolean? = null,
  val data: List<Snippet?>? = null,
  val filter: SnippetFilter? = null,
  val error: String? = null
) : ModelStateData()
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): MainModelStateData {
      val state = pigeonVar_list[0] as ModelState?
      val isLoading = pigeonVar_list[1] as Boolean?
      val data = pigeonVar_list[2] as List<Snippet?>?
      val filter = pigeonVar_list[3] as SnippetFilter?
      val error = pigeonVar_list[4] as String?
      return MainModelStateData(state, isLoading, data, filter, error)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      state,
      isLoading,
      data,
      filter,
      error,
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class MainModelEventData (
  val event: MainModelEvent? = null,
  val message: String? = null
) : ModelEventData()
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): MainModelEventData {
      val event = pigeonVar_list[0] as MainModelEvent?
      val message = pigeonVar_list[1] as String?
      return MainModelEventData(event, message)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      event,
      message,
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class DetailsModelStateData (
  val state: ModelState? = null,
  val isLoading: Boolean? = null,
  val data: Snippet? = null,
  val error: String? = null
) : ModelStateData()
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): DetailsModelStateData {
      val state = pigeonVar_list[0] as ModelState?
      val isLoading = pigeonVar_list[1] as Boolean?
      val data = pigeonVar_list[2] as Snippet?
      val error = pigeonVar_list[3] as String?
      return DetailsModelStateData(state, isLoading, data, error)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      state,
      isLoading,
      data,
      error,
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class DetailsModelEventData (
  val event: DetailsModelEvent? = null,
  val value: String? = null
) : ModelEventData()
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): DetailsModelEventData {
      val event = pigeonVar_list[0] as DetailsModelEvent?
      val value = pigeonVar_list[1] as String?
      return DetailsModelEventData(event, value)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      event,
      value,
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class LoginModelStateData (
  val state: ModelState? = null,
  val isLoading: Boolean? = null
) : ModelStateData()
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): LoginModelStateData {
      val state = pigeonVar_list[0] as ModelState?
      val isLoading = pigeonVar_list[1] as Boolean?
      return LoginModelStateData(state, isLoading)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      state,
      isLoading,
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class LoginModelEventData (
  val event: LoginModelEvent? = null
) : ModelEventData()
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): LoginModelEventData {
      val event = pigeonVar_list[0] as LoginModelEvent?
      return LoginModelEventData(event)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      event,
    )
  }
}
private open class DataModelPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          SnippetLanguageType.ofRaw(it.toInt())
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          SnippetFilterType.ofRaw(it.toInt())
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          UserReaction.ofRaw(it.toInt())
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          ModelState.ofRaw(it.toInt())
        }
      }
      133.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          MainModelEvent.ofRaw(it.toInt())
        }
      }
      134.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          DetailsModelEvent.ofRaw(it.toInt())
        }
      }
      135.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          LoginModelEvent.ofRaw(it.toInt())
        }
      }
      136.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          Snippet.fromList(it)
        }
      }
      137.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          SnippetCode.fromList(it)
        }
      }
      138.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          SyntaxToken.fromList(it)
        }
      }
      139.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          SnippetLanguage.fromList(it)
        }
      }
      140.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          Owner.fromList(it)
        }
      }
      141.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          SnippetFilter.fromList(it)
        }
      }
      142.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          MainModelStateData.fromList(it)
        }
      }
      143.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          MainModelEventData.fromList(it)
        }
      }
      144.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          DetailsModelStateData.fromList(it)
        }
      }
      145.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          DetailsModelEventData.fromList(it)
        }
      }
      146.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          LoginModelStateData.fromList(it)
        }
      }
      147.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          LoginModelEventData.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is SnippetLanguageType -> {
        stream.write(129)
        writeValue(stream, value.raw)
      }
      is SnippetFilterType -> {
        stream.write(130)
        writeValue(stream, value.raw)
      }
      is UserReaction -> {
        stream.write(131)
        writeValue(stream, value.raw)
      }
      is ModelState -> {
        stream.write(132)
        writeValue(stream, value.raw)
      }
      is MainModelEvent -> {
        stream.write(133)
        writeValue(stream, value.raw)
      }
      is DetailsModelEvent -> {
        stream.write(134)
        writeValue(stream, value.raw)
      }
      is LoginModelEvent -> {
        stream.write(135)
        writeValue(stream, value.raw)
      }
      is Snippet -> {
        stream.write(136)
        writeValue(stream, value.toList())
      }
      is SnippetCode -> {
        stream.write(137)
        writeValue(stream, value.toList())
      }
      is SyntaxToken -> {
        stream.write(138)
        writeValue(stream, value.toList())
      }
      is SnippetLanguage -> {
        stream.write(139)
        writeValue(stream, value.toList())
      }
      is Owner -> {
        stream.write(140)
        writeValue(stream, value.toList())
      }
      is SnippetFilter -> {
        stream.write(141)
        writeValue(stream, value.toList())
      }
      is MainModelStateData -> {
        stream.write(142)
        writeValue(stream, value.toList())
      }
      is MainModelEventData -> {
        stream.write(143)
        writeValue(stream, value.toList())
      }
      is DetailsModelStateData -> {
        stream.write(144)
        writeValue(stream, value.toList())
      }
      is DetailsModelEventData -> {
        stream.write(145)
        writeValue(stream, value.toList())
      }
      is LoginModelStateData -> {
        stream.write(146)
        writeValue(stream, value.toList())
      }
      is LoginModelEventData -> {
        stream.write(147)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}

val DataModelPigeonMethodCodec = StandardMethodCodec(DataModelPigeonCodec());


private class DataModelPigeonStreamHandler<T>(
    val wrapper: DataModelPigeonEventChannelWrapper<T>
) : EventChannel.StreamHandler {
  var pigeonSink: PigeonEventSink<T>? = null

  override fun onListen(p0: Any?, sink: EventChannel.EventSink) {
    pigeonSink = PigeonEventSink<T>(sink)
    wrapper.onListen(p0, pigeonSink!!)
  }

  override fun onCancel(p0: Any?) {
    pigeonSink = null
    wrapper.onCancel(p0)
  }
}

interface DataModelPigeonEventChannelWrapper<T> {
  open fun onListen(p0: Any?, sink: PigeonEventSink<T>) {}

  open fun onCancel(p0: Any?) {}
}

class PigeonEventSink<T>(private val sink: EventChannel.EventSink) {
  fun success(value: T) {
    sink.success(value)
  }

  fun error(errorCode: String, errorMessage: String?, errorDetails: Any?) {
    sink.error(errorCode, errorMessage, errorDetails)
  }

  fun endOfStream() {
    sink.endOfStream()
  }
}
      
abstract class ChannelStateStreamHandler : DataModelPigeonEventChannelWrapper<ModelStateData> {
  companion object {
    fun register(messenger: BinaryMessenger, streamHandler: ChannelStateStreamHandler, instanceName: String = "") {
      var channelName: String = "dev.flutter.pigeon.flutter_module.ChannelModelEventApi.channelState"
      if (instanceName.isNotEmpty()) {
        channelName += ".$instanceName"
      }
      val internalStreamHandler = DataModelPigeonStreamHandler<ModelStateData>(streamHandler)
      EventChannel(messenger, channelName, DataModelPigeonMethodCodec).setStreamHandler(internalStreamHandler)
    }
  }
}
      
abstract class ChannelEventStreamHandler : DataModelPigeonEventChannelWrapper<ModelEventData> {
  companion object {
    fun register(messenger: BinaryMessenger, streamHandler: ChannelEventStreamHandler, instanceName: String = "") {
      var channelName: String = "dev.flutter.pigeon.flutter_module.ChannelModelEventApi.channelEvent"
      if (instanceName.isNotEmpty()) {
        channelName += ".$instanceName"
      }
      val internalStreamHandler = DataModelPigeonStreamHandler<ModelEventData>(streamHandler)
      EventChannel(messenger, channelName, DataModelPigeonMethodCodec).setStreamHandler(internalStreamHandler)
    }
  }
}
      
/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface ChannelMainModel {
  fun resetEvent()
  fun initState()
  fun filterLanguage(language: String, isSelected: Boolean)
  fun filterScope(scope: String)
  fun logOut()

  companion object {
    /** The codec used by ChannelMainModel. */
    val codec: MessageCodec<Any?> by lazy {
      DataModelPigeonCodec()
    }
    /** Sets up an instance of `ChannelMainModel` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: ChannelMainModel?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      val taskQueue = binaryMessenger.makeBackgroundTaskQueue()
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_module.ChannelMainModel.resetEvent$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.resetEvent()
              listOf(null)
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_module.ChannelMainModel.initState$separatedMessageChannelSuffix", codec, taskQueue)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.initState()
              listOf(null)
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_module.ChannelMainModel.filterLanguage$separatedMessageChannelSuffix", codec, taskQueue)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val languageArg = args[0] as String
            val isSelectedArg = args[1] as Boolean
            val wrapped: List<Any?> = try {
              api.filterLanguage(languageArg, isSelectedArg)
              listOf(null)
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_module.ChannelMainModel.filterScope$separatedMessageChannelSuffix", codec, taskQueue)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val scopeArg = args[0] as String
            val wrapped: List<Any?> = try {
              api.filterScope(scopeArg)
              listOf(null)
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_module.ChannelMainModel.logOut$separatedMessageChannelSuffix", codec, taskQueue)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.logOut()
              listOf(null)
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface ChannelDetailsModel {
  fun resetEvent()
  fun load(uuid: String)
  fun toggleFavorite()
  fun saveImage(image: ByteArray)
  fun copyToClipboard()
  fun shareImage(image: ByteArray)
  fun delete()

  companion object {
    /** The codec used by ChannelDetailsModel. */
    val codec: MessageCodec<Any?> by lazy {
      DataModelPigeonCodec()
    }
    /** Sets up an instance of `ChannelDetailsModel` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: ChannelDetailsModel?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_module.ChannelDetailsModel.resetEvent$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.resetEvent()
              listOf(null)
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_module.ChannelDetailsModel.load$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val uuidArg = args[0] as String
            val wrapped: List<Any?> = try {
              api.load(uuidArg)
              listOf(null)
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_module.ChannelDetailsModel.toggleFavorite$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.toggleFavorite()
              listOf(null)
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_module.ChannelDetailsModel.saveImage$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val imageArg = args[0] as ByteArray
            val wrapped: List<Any?> = try {
              api.saveImage(imageArg)
              listOf(null)
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_module.ChannelDetailsModel.copyToClipboard$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.copyToClipboard()
              listOf(null)
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_module.ChannelDetailsModel.shareImage$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val imageArg = args[0] as ByteArray
            val wrapped: List<Any?> = try {
              api.shareImage(imageArg)
              listOf(null)
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_module.ChannelDetailsModel.delete$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.delete()
              listOf(null)
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface ChannelLoginModel {
  fun loginOrRegister(email: String, password: String)
  fun checkLoginState()
  fun resetEvent()

  companion object {
    /** The codec used by ChannelLoginModel. */
    val codec: MessageCodec<Any?> by lazy {
      DataModelPigeonCodec()
    }
    /** Sets up an instance of `ChannelLoginModel` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: ChannelLoginModel?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_module.ChannelLoginModel.loginOrRegister$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val emailArg = args[0] as String
            val passwordArg = args[1] as String
            val wrapped: List<Any?> = try {
              api.loginOrRegister(emailArg, passwordArg)
              listOf(null)
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_module.ChannelLoginModel.checkLoginState$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.checkLoginState()
              listOf(null)
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_module.ChannelLoginModel.resetEvent$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.resetEvent()
              listOf(null)
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
